# Generated by Django 5.0.7 on 2024-07-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='short_url',
        ),
        migrations.AddField(
            model_name='url',
            name='short_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
