# Generated by Django 5.0.7 on 2024-07-13 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_url_short_url_url_short_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='short_code',
            new_name='short_url',
        ),
    ]
